// Code generated by the Encore 1.48.13 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly ai: ai.ServiceClient
    public readonly analytics: analytics.ServiceClient
    public readonly billing: billing.ServiceClient
    public readonly notes: notes.ServiceClient
    public readonly notifications: notifications.ServiceClient
    public readonly projects: projects.ServiceClient
    public readonly supabase: supabase.ServiceClient
    public readonly workflows: workflows.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.ai = new ai.ServiceClient(base)
        this.analytics = new analytics.ServiceClient(base)
        this.billing = new billing.ServiceClient(base)
        this.notes = new notes.ServiceClient(base)
        this.notifications = new notifications.ServiceClient(base)
        this.projects = new projects.ServiceClient(base)
        this.supabase = new supabase.ServiceClient(base)
        this.workflows = new workflows.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { advancedAnalysis as api_ai_advanced_analysis_advancedAnalysis } from "~backend/ai/advanced_analysis";
import { analyzeTranscript as api_ai_analyze_analyzeTranscript } from "~backend/ai/analyze";
import { chat as api_ai_chat_chat } from "~backend/ai/chat";
import {
    classify as api_ai_cohere_classify,
    generate as api_ai_cohere_generate,
    semanticSearch as api_ai_cohere_semanticSearch
} from "~backend/ai/cohere";
import { detectLanguage as api_ai_detect_language_detectLanguage } from "~backend/ai/detect_language";
import {
    analyzeMeetingPatterns as api_ai_meeting_preparation_analyzeMeetingPatterns,
    generateMeetingTemplate as api_ai_meeting_preparation_generateMeetingTemplate,
    prepareMeeting as api_ai_meeting_preparation_prepareMeeting
} from "~backend/ai/meeting_preparation";
import { generateSmartInsights as api_ai_smart_insights_generateSmartInsights } from "~backend/ai/smart_insights";
import { summarize as api_ai_summarize_summarize } from "~backend/ai/summarize";
import { transcribe as api_ai_transcribe_transcribe } from "~backend/ai/transcribe";
import {
    createWorkflow as api_ai_workflow_automation_createWorkflow,
    executeWorkflows as api_ai_workflow_automation_executeWorkflows,
    generateSmartTemplate as api_ai_workflow_automation_generateSmartTemplate,
    listWorkflows as api_ai_workflow_automation_listWorkflows
} from "~backend/ai/workflow_automation";

export namespace ai {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.advancedAnalysis = this.advancedAnalysis.bind(this)
            this.analyzeMeetingPatterns = this.analyzeMeetingPatterns.bind(this)
            this.analyzeTranscript = this.analyzeTranscript.bind(this)
            this.chat = this.chat.bind(this)
            this.classify = this.classify.bind(this)
            this.createWorkflow = this.createWorkflow.bind(this)
            this.detectLanguage = this.detectLanguage.bind(this)
            this.executeWorkflows = this.executeWorkflows.bind(this)
            this.generate = this.generate.bind(this)
            this.generateMeetingTemplate = this.generateMeetingTemplate.bind(this)
            this.generateSmartInsights = this.generateSmartInsights.bind(this)
            this.generateSmartTemplate = this.generateSmartTemplate.bind(this)
            this.listWorkflows = this.listWorkflows.bind(this)
            this.prepareMeeting = this.prepareMeeting.bind(this)
            this.semanticSearch = this.semanticSearch.bind(this)
            this.summarize = this.summarize.bind(this)
            this.transcribe = this.transcribe.bind(this)
        }

        /**
         * Performs advanced AI analysis with multiple sophisticated insights.
         */
        public async advancedAnalysis(params: RequestType<typeof api_ai_advanced_analysis_advancedAnalysis>): Promise<ResponseType<typeof api_ai_advanced_analysis_advancedAnalysis>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/advanced-analysis`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_advanced_analysis_advancedAnalysis>
        }

        /**
         * Analyzes meeting patterns and provides insights for better meeting planning.
         */
        public async analyzeMeetingPatterns(params: RequestType<typeof api_ai_meeting_preparation_analyzeMeetingPatterns>): Promise<ResponseType<typeof api_ai_meeting_preparation_analyzeMeetingPatterns>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/analyze-meeting-patterns`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_meeting_preparation_analyzeMeetingPatterns>
        }

        /**
         * Analyzes transcript content for various insights using advanced AI.
         */
        public async analyzeTranscript(params: RequestType<typeof api_ai_analyze_analyzeTranscript>): Promise<ResponseType<typeof api_ai_analyze_analyzeTranscript>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/analyze`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_analyze_analyzeTranscript>
        }

        /**
         * Provides AI-powered chat assistance for notes and recordings.
         */
        public async chat(params: RequestType<typeof api_ai_chat_chat>): Promise<ResponseType<typeof api_ai_chat_chat>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/chat`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_chat_chat>
        }

        /**
         * Classifies text using Cohere's classification models.
         */
        public async classify(params: RequestType<typeof api_ai_cohere_classify>): Promise<ResponseType<typeof api_ai_cohere_classify>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/cohere/classify`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_cohere_classify>
        }

        /**
         * Creates a new automated workflow with triggers and actions.
         */
        public async createWorkflow(params: RequestType<typeof api_ai_workflow_automation_createWorkflow>): Promise<ResponseType<typeof api_ai_workflow_automation_createWorkflow>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/workflows`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_workflow_automation_createWorkflow>
        }

        /**
         * Detects the language of audio using OpenAI Whisper API.
         */
        public async detectLanguage(params: RequestType<typeof api_ai_detect_language_detectLanguage>): Promise<ResponseType<typeof api_ai_detect_language_detectLanguage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/detect-language`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_detect_language_detectLanguage>
        }

        /**
         * Executes workflows based on meeting content and triggers.
         */
        public async executeWorkflows(params: RequestType<typeof api_ai_workflow_automation_executeWorkflows>): Promise<ResponseType<typeof api_ai_workflow_automation_executeWorkflows>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/workflows/execute`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_workflow_automation_executeWorkflows>
        }

        /**
         * Generates text using Cohere's language models.
         */
        public async generate(params: RequestType<typeof api_ai_cohere_generate>): Promise<ResponseType<typeof api_ai_cohere_generate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/cohere/generate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_cohere_generate>
        }

        /**
         * Generates meeting templates based on type and requirements.
         */
        public async generateMeetingTemplate(params: RequestType<typeof api_ai_meeting_preparation_generateMeetingTemplate>): Promise<ResponseType<typeof api_ai_meeting_preparation_generateMeetingTemplate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/generate-meeting-template`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_meeting_preparation_generateMeetingTemplate>
        }

        /**
         * Generates smart insights and predictions based on user's meeting patterns and content.
         */
        public async generateSmartInsights(params: RequestType<typeof api_ai_smart_insights_generateSmartInsights>): Promise<ResponseType<typeof api_ai_smart_insights_generateSmartInsights>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/smart-insights`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_smart_insights_generateSmartInsights>
        }

        /**
         * Generates smart templates for various communication needs.
         */
        public async generateSmartTemplate(params: RequestType<typeof api_ai_workflow_automation_generateSmartTemplate>): Promise<ResponseType<typeof api_ai_workflow_automation_generateSmartTemplate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/smart-template`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_workflow_automation_generateSmartTemplate>
        }

        /**
         * Lists all workflows.
         */
        public async listWorkflows(): Promise<ResponseType<typeof api_ai_workflow_automation_listWorkflows>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/workflows`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_workflow_automation_listWorkflows>
        }

        /**
         * Generates comprehensive meeting preparation materials using AI analysis of previous meetings.
         */
        public async prepareMeeting(params: RequestType<typeof api_ai_meeting_preparation_prepareMeeting>): Promise<ResponseType<typeof api_ai_meeting_preparation_prepareMeeting>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/prepare-meeting`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_meeting_preparation_prepareMeeting>
        }

        /**
         * Performs semantic search using Cohere's embedding models.
         */
        public async semanticSearch(params: RequestType<typeof api_ai_cohere_semanticSearch>): Promise<ResponseType<typeof api_ai_cohere_semanticSearch>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/cohere/search`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_cohere_semanticSearch>
        }

        /**
         * Generates a summary of the provided transcript using OpenAI.
         */
        public async summarize(params: RequestType<typeof api_ai_summarize_summarize>): Promise<ResponseType<typeof api_ai_summarize_summarize>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/summarize`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_summarize_summarize>
        }

        /**
         * Transcribes audio to text using OpenAI Whisper API with automatic language detection and English translation.
         */
        public async transcribe(params: RequestType<typeof api_ai_transcribe_transcribe>): Promise<ResponseType<typeof api_ai_transcribe_transcribe>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/transcribe`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_transcribe_transcribe>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    capturePageView as api_analytics_posthog_capturePageView,
    getInsights as api_analytics_posthog_getInsights,
    identifyUser as api_analytics_posthog_identifyUser,
    trackEvent as api_analytics_posthog_trackEvent
} from "~backend/analytics/posthog";

export namespace analytics {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.capturePageView = this.capturePageView.bind(this)
            this.getInsights = this.getInsights.bind(this)
            this.identifyUser = this.identifyUser.bind(this)
            this.trackEvent = this.trackEvent.bind(this)
        }

        /**
         * Captures page view events for analytics.
         */
        public async capturePageView(params: RequestType<typeof api_analytics_posthog_capturePageView>): Promise<ResponseType<typeof api_analytics_posthog_capturePageView>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/pageview`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_posthog_capturePageView>
        }

        /**
         * Gets analytics insights from PostHog.
         */
        public async getInsights(params: RequestType<typeof api_analytics_posthog_getInsights>): Promise<ResponseType<typeof api_analytics_posthog_getInsights>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                events:    params.events?.map((v) => v),
                timeframe: params.timeframe === undefined ? undefined : String(params.timeframe),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/insights`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_posthog_getInsights>
        }

        /**
         * Identifies a user with properties for analytics.
         */
        public async identifyUser(params: RequestType<typeof api_analytics_posthog_identifyUser>): Promise<ResponseType<typeof api_analytics_posthog_identifyUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/identify`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_posthog_identifyUser>
        }

        /**
         * Tracks custom events for analytics.
         */
        public async trackEvent(params: RequestType<typeof api_analytics_posthog_trackEvent>): Promise<ResponseType<typeof api_analytics_posthog_trackEvent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/track`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_posthog_trackEvent>
        }
    }
}


export namespace auth {
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createCheckoutSession as api_billing_billing_createCheckoutSession,
    createPortalSession as api_billing_billing_createPortalSession,
    getSubscription as api_billing_billing_getSubscription,
    handleWebhook as api_billing_billing_handleWebhook
} from "~backend/billing/billing";

export namespace billing {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createCheckoutSession = this.createCheckoutSession.bind(this)
            this.createPortalSession = this.createPortalSession.bind(this)
            this.getSubscription = this.getSubscription.bind(this)
            this.handleWebhook = this.handleWebhook.bind(this)
        }

        /**
         * Creates a Stripe checkout session for subscription.
         */
        public async createCheckoutSession(params: RequestType<typeof api_billing_billing_createCheckoutSession>): Promise<ResponseType<typeof api_billing_billing_createCheckoutSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/billing/checkout`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_billing_billing_createCheckoutSession>
        }

        /**
         * Creates a Stripe customer portal session.
         */
        public async createPortalSession(params: RequestType<typeof api_billing_billing_createPortalSession>): Promise<ResponseType<typeof api_billing_billing_createPortalSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/billing/portal`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_billing_billing_createPortalSession>
        }

        /**
         * Gets user's subscription and usage information.
         */
        public async getSubscription(): Promise<ResponseType<typeof api_billing_billing_getSubscription>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/billing/subscription`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_billing_billing_getSubscription>
        }

        /**
         * Handles Stripe webhooks for subscription events.
         */
        public async handleWebhook(params: RequestType<typeof api_billing_billing_handleWebhook>): Promise<void> {
            await this.baseClient.callTypedAPI(`/billing/webhook`, {method: "POST", body: JSON.stringify(params)})
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getAnalytics as api_notes_analytics_getAnalytics } from "~backend/notes/analytics";
import { createNote as api_notes_create_createNote } from "~backend/notes/create";
import { deleteNote as api_notes_delete_deleteNote } from "~backend/notes/delete";
import { exportNotes as api_notes_export_exportNotes } from "~backend/notes/export";
import { getNote as api_notes_get_getNote } from "~backend/notes/get";
import { listNotes as api_notes_list_listNotes } from "~backend/notes/list";
import { searchNotes as api_notes_search_searchNotes } from "~backend/notes/search";
import { updateNote as api_notes_update_updateNote } from "~backend/notes/update";

export namespace notes {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createNote = this.createNote.bind(this)
            this.deleteNote = this.deleteNote.bind(this)
            this.exportNotes = this.exportNotes.bind(this)
            this.getAnalytics = this.getAnalytics.bind(this)
            this.getNote = this.getNote.bind(this)
            this.listNotes = this.listNotes.bind(this)
            this.searchNotes = this.searchNotes.bind(this)
            this.updateNote = this.updateNote.bind(this)
        }

        /**
         * Creates a new note with transcript and summary.
         */
        public async createNote(params: RequestType<typeof api_notes_create_createNote>): Promise<ResponseType<typeof api_notes_create_createNote>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notes`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notes_create_createNote>
        }

        /**
         * Deletes a note by ID.
         */
        public async deleteNote(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/notes/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Exports notes in various formats.
         */
        public async exportNotes(params: RequestType<typeof api_notes_export_exportNotes>): Promise<ResponseType<typeof api_notes_export_exportNotes>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notes/export`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notes_export_exportNotes>
        }

        /**
         * Provides analytics and insights about user's recordings.
         */
        public async getAnalytics(): Promise<ResponseType<typeof api_notes_analytics_getAnalytics>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notes/analytics`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notes_analytics_getAnalytics>
        }

        /**
         * Retrieves a specific note by ID.
         */
        public async getNote(params: { id: number }): Promise<ResponseType<typeof api_notes_get_getNote>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notes/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notes_get_getNote>
        }

        /**
         * Retrieves all notes with optional search and pagination.
         */
        public async listNotes(params: RequestType<typeof api_notes_list_listNotes>): Promise<ResponseType<typeof api_notes_list_listNotes>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:     params.limit === undefined ? undefined : String(params.limit),
                offset:    params.offset === undefined ? undefined : String(params.offset),
                projectId: params.projectId === undefined ? undefined : String(params.projectId),
                search:    params.search,
                tags:      params.tags,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notes`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notes_list_listNotes>
        }

        /**
         * Advanced search across notes with semantic search capabilities.
         */
        public async searchNotes(params: RequestType<typeof api_notes_search_searchNotes>): Promise<ResponseType<typeof api_notes_search_searchNotes>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                filters: params.filters,
                limit:   params.limit === undefined ? undefined : String(params.limit),
                offset:  params.offset === undefined ? undefined : String(params.offset),
                query:   params.query,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notes/search`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notes_search_searchNotes>
        }

        /**
         * Updates an existing note.
         */
        public async updateNote(params: RequestType<typeof api_notes_update_updateNote>): Promise<ResponseType<typeof api_notes_update_updateNote>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                isPublic:   params.isPublic,
                projectId:  params.projectId,
                summary:    params.summary,
                tags:       params.tags,
                title:      params.title,
                transcript: params.transcript,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notes/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notes_update_updateNote>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    sendBillingNotification as api_notifications_resend_sendBillingNotification,
    sendEmail as api_notifications_resend_sendEmail,
    sendRecordingNotification as api_notifications_resend_sendRecordingNotification,
    sendWelcomeEmail as api_notifications_resend_sendWelcomeEmail
} from "~backend/notifications/resend";

export namespace notifications {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.sendBillingNotification = this.sendBillingNotification.bind(this)
            this.sendEmail = this.sendEmail.bind(this)
            this.sendRecordingNotification = this.sendRecordingNotification.bind(this)
            this.sendWelcomeEmail = this.sendWelcomeEmail.bind(this)
        }

        /**
         * Sends billing-related notification emails.
         */
        public async sendBillingNotification(params: RequestType<typeof api_notifications_resend_sendBillingNotification>): Promise<ResponseType<typeof api_notifications_resend_sendBillingNotification>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/billing`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_resend_sendBillingNotification>
        }

        /**
         * Sends a custom email using Resend.
         */
        public async sendEmail(params: RequestType<typeof api_notifications_resend_sendEmail>): Promise<ResponseType<typeof api_notifications_resend_sendEmail>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/email`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_resend_sendEmail>
        }

        /**
         * Sends a notification email when a recording is processed.
         */
        public async sendRecordingNotification(params: RequestType<typeof api_notifications_resend_sendRecordingNotification>): Promise<ResponseType<typeof api_notifications_resend_sendRecordingNotification>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/recording`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_resend_sendRecordingNotification>
        }

        /**
         * Sends a welcome email to new users.
         */
        public async sendWelcomeEmail(params: RequestType<typeof api_notifications_resend_sendWelcomeEmail>): Promise<ResponseType<typeof api_notifications_resend_sendWelcomeEmail>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/welcome`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_resend_sendWelcomeEmail>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createProject as api_projects_create_createProject } from "~backend/projects/create";
import { deleteProject as api_projects_delete_deleteProject } from "~backend/projects/delete";
import { getProject as api_projects_get_getProject } from "~backend/projects/get";
import { listProjects as api_projects_list_listProjects } from "~backend/projects/list";
import { updateProject as api_projects_update_updateProject } from "~backend/projects/update";

export namespace projects {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createProject = this.createProject.bind(this)
            this.deleteProject = this.deleteProject.bind(this)
            this.getProject = this.getProject.bind(this)
            this.listProjects = this.listProjects.bind(this)
            this.updateProject = this.updateProject.bind(this)
        }

        /**
         * Creates a new project.
         */
        public async createProject(params: RequestType<typeof api_projects_create_createProject>): Promise<ResponseType<typeof api_projects_create_createProject>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_create_createProject>
        }

        /**
         * Deletes a project.
         */
        public async deleteProject(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves a specific project by ID.
         */
        public async getProject(params: { id: number }): Promise<ResponseType<typeof api_projects_get_getProject>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_get_getProject>
        }

        /**
         * Lists all projects for the current user or organization.
         */
        public async listProjects(): Promise<ResponseType<typeof api_projects_list_listProjects>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_list_listProjects>
        }

        /**
         * Updates a project.
         */
        public async updateProject(params: RequestType<typeof api_projects_update_updateProject>): Promise<ResponseType<typeof api_projects_update_updateProject>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description: params.description,
                name:        params.name,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_update_updateProject>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getAnalytics as api_supabase_analytics_getAnalytics,
    getUserActivities as api_supabase_analytics_getUserActivities,
    getUserPreferences as api_supabase_analytics_getUserPreferences,
    logActivity as api_supabase_analytics_logActivity,
    updateUserPreferences as api_supabase_analytics_updateUserPreferences
} from "~backend/supabase/analytics";

export namespace supabase {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getAnalytics = this.getAnalytics.bind(this)
            this.getUserActivities = this.getUserActivities.bind(this)
            this.getUserPreferences = this.getUserPreferences.bind(this)
            this.logActivity = this.logActivity.bind(this)
            this.updateUserPreferences = this.updateUserPreferences.bind(this)
        }

        /**
         * Gets analytics data from Supabase.
         */
        public async getAnalytics(params: RequestType<typeof api_supabase_analytics_getAnalytics>): Promise<ResponseType<typeof api_supabase_analytics_getAnalytics>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                timeframe: params.timeframe === undefined ? undefined : String(params.timeframe),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/supabase/analytics`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_supabase_analytics_getAnalytics>
        }

        /**
         * Gets user activities from Supabase.
         */
        public async getUserActivities(params: RequestType<typeof api_supabase_analytics_getUserActivities>): Promise<ResponseType<typeof api_supabase_analytics_getUserActivities>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                activityType: params.activityType,
                limit:        params.limit === undefined ? undefined : String(params.limit),
                offset:       params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/supabase/activities`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_supabase_analytics_getUserActivities>
        }

        /**
         * Gets user preferences from Supabase.
         */
        public async getUserPreferences(): Promise<ResponseType<typeof api_supabase_analytics_getUserPreferences>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/supabase/preferences`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_supabase_analytics_getUserPreferences>
        }

        /**
         * Logs user activity to Supabase for analytics.
         */
        public async logActivity(params: RequestType<typeof api_supabase_analytics_logActivity>): Promise<ResponseType<typeof api_supabase_analytics_logActivity>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/supabase/activity`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_supabase_analytics_logActivity>
        }

        /**
         * Updates user preferences in Supabase.
         */
        public async updateUserPreferences(params: RequestType<typeof api_supabase_analytics_updateUserPreferences>): Promise<ResponseType<typeof api_supabase_analytics_updateUserPreferences>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/supabase/preferences`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_supabase_analytics_updateUserPreferences>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createWebhook as api_workflows_make_createWebhook,
    getExecution as api_workflows_make_getExecution,
    triggerWorkflow as api_workflows_make_triggerWorkflow
} from "~backend/workflows/make";

export namespace workflows {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createWebhook = this.createWebhook.bind(this)
            this.getExecution = this.getExecution.bind(this)
            this.triggerWorkflow = this.triggerWorkflow.bind(this)
        }

        /**
         * Creates a webhook for Make.com integration.
         */
        public async createWebhook(params: RequestType<typeof api_workflows_make_createWebhook>): Promise<ResponseType<typeof api_workflows_make_createWebhook>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/workflows/make/webhooks`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_workflows_make_createWebhook>
        }

        /**
         * Gets the status and result of a workflow execution.
         */
        public async getExecution(params: { executionId: string }): Promise<ResponseType<typeof api_workflows_make_getExecution>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/workflows/make/executions/${encodeURIComponent(params.executionId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_workflows_make_getExecution>
        }

        /**
         * Triggers a Make.com workflow scenario.
         */
        public async triggerWorkflow(params: RequestType<typeof api_workflows_make_triggerWorkflow>): Promise<ResponseType<typeof api_workflows_make_triggerWorkflow>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/workflows/make/trigger`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_workflows_make_triggerWorkflow>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.13)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
